# Generated by Django 4.2.10 on 2024-02-07 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_shippingaddress_order_shippingaddress_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='_id',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='shippingPrice',
        ),
    ]
